### ISSUE TITLE
panic: runtime error: slice bounds out of range [-1:]

### ISSUE THREAD

**Issue by dparbhakar** [estafette/estafette-k8s-node-compactor#6]
Hello,

While scaling up a cluster that was off during the night, here is what I got :

`<nil> INF Starting estafette-k8s-node-compactor version 1.1.0... branch=1.1.0 buildDate=2020-05-08T14:07:08Z goVersion=go1.14.2 os=linux revision=a387e14626ed4e7c7a6d336680bd64e06c4667a9
<nil> DBG Serving /liveness endpoint... port=:5000
<nil> DBG Serving Prometheus metrics... port=:9101
<nil> INF Running node compaction process
<nil> INF Node pool: node-pool-main
panic: runtime error: slice bounds out of range [-1:]

goroutine 49 [running]:
main.memoryReqStrToMemoryMB(0x1014fb0, 0x1, 0xb40ab4)
        /estafette-work/main.go:605 +0xcf
main.calculateNodeStats(0xc0009a58c0, 0xc000184480, 0xd, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /estafette-work/main.go:569 +0x296
main.collectNodeInfos(0xc0009e6180, 0xc, 0x10, 0xc0000ae000, 0x148, 0x200, 0x1, 0x3fe8000000000000, 0x5, 0x0, ...)
        /estafette-work/main.go:503 +0x166
main.runNodeCompaction(0xc00020a390)
        /estafette-work/main.go:220 +0x8d0
main.main.func1(0xc00020a390, 0xc000294000)
        /estafette-work/main.go:170 +0x34
created by main.main
        /estafette-work/main.go:164 +0x274
`

To fix it, I had to reapply the chart (no diff).
Killing the pod or a kubectl rollout restart wouldn't work.

Any clues on this ?

Thanks,

**Comment by markvincze** [comment]
Hi @frog-network,

It's hard to say what's wrong exactly, but based on the stack and the error message the problem is probably in these lines of the `memoryReqStrToMemoryMB` function:

```
func memoryReqStrToMemoryMB(str string) int {
	unit := str[len(str)-2:]
	str = str[:len(str)-2] // For example: 2000Mi
```

The `str` string here is created earlier like this:

```
	allocatableMemory := memoryReqStrToMemoryMB(*node.Status.Allocatable["memory"].String_)
```

Where we expect the string describing the allocatable memory to be in the format `12345Mi` or `12345Ki`.  
The error message suggest that the string in your case was less than 2 characters long.
Is this something you can reproduce? If yes, can you check one of the nodes with `kubectl describe node {nodename}`, and check the `memory` field under `Allocatable` in the output? I checked it in one of our clusters, and it was in this format:

```
Allocatable:
 memory:                     12698416Ki
```

Which is the expected format, for which the parsing works. But it might be that in some situations the format is different, and we didn't prepare the code to handle it, so it'd be interesting to learn what it was in your case.

**Comment by Fryuni** [comment]
By the docs for [Quantity](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/), it is valid to have a value without a suffix:
> Note that `<suffix>` may be empty, from the "" case in `<decimalSI>`

Any integer between -9 and 99 will give this panic. Since this is a memory field and there is no negative memory, 0 to 9.

During initialization, while the node is not yet ready, it might be reporting 0 allocatable memory, or not reporting that at all and the client filling in with 0 (haven't checked that).
